org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

android_git_version_version=0.4.14
shadow_version=9.2.2

# Fabric / Minecraft 26.2
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_api_version=0.156.0+26.2

# Mod properties
mod_version=1.0.0
maven_group=com.github.arm32x

# Libraries
msgpack_java_version=0.9.3
junit_version=5.9.2
jqwik_version=1.7.3
assertj_version=3.24.2
