# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
# Gradle Plugins
android_git_version_version=0.4.14
loom_version=1.17.12
shadow_version=9.4.2
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.2
loader_version=0.19.3
# Dependencies
# check these on https://modmuss50.me/fabric.html
fabric_version=0.153.0+26.2
msgpack_java_version=0.9.3
# Test dependencies
junit_version=5.9.2
junit_platform_version=1.9.2
jqwik_version=1.7.3
assertj_version=3.24.2
